// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsnjca_d89TRxgU1c_xpYZ7sdDhlnN3MY',
    appId: '1:1059928848546:web:37a0dc3298abc32a3a7ffb',
    messagingSenderId: '1059928848546',
    projectId: 'salonbooking-af1df',
    authDomain: 'salonbooking-af1df.firebaseapp.com',
    storageBucket: 'salonbooking-af1df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYoX-14ujLDDSXt2MKSTKJuDrSAp4VHvw',
    appId: '1:1059928848546:android:463373ab676c67813a7ffb',
    messagingSenderId: '1059928848546',
    projectId: 'salonbooking-af1df',
    storageBucket: 'salonbooking-af1df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBm3HqN6hzTcKeJWqsDGoGyaZylWCmwcg',
    appId: '1:1059928848546:ios:1323ce2025ea27393a7ffb',
    messagingSenderId: '1059928848546',
    projectId: 'salonbooking-af1df',
    storageBucket: 'salonbooking-af1df.firebasestorage.app',
    iosBundleId: 'com.salonbooking.salonbooking',
  );
}
